// Generated by xxx.ps1 on 2026-02-25 14:15:35
using System.ComponentModel; 
namespace BirImza.Types.Shared
{


    public enum SignatureLevelForPades
    {
        //paslUnknown = 0,
        //paslGeneric = 1,
        //paslBaselineB = 2,
        //paslBaselineT = 3,
        //paslBaselineLT = 4,
        //paslBaselineLTA = 5,
        paslBES = 6,
        //paslEPES = 7,
        paslLTV = 8
    }

    public enum SignatureLevelForCades
    {
        aslBES = 6,                 // BES (Basic Electronic Signature)
        //aslEPES = 7,                // EPES (Electronic Signature with an Explicit Policy)
        aslT = 8,                   // T (Timestamped)
        //aslC = 9,                   // C (T with revocation references)
        //aslXType1 = 11,             // X Type 1 (C with an ES-C timestamp, CAdES only)
        //aslXType2 = 12,             // X Type 2 (C with a CertsAndCRLs timestamp, CAdES only)
        //aslXLType1 = 14,            // X-L Type 1 (C with revocation values and an ES-C timestamp, CAdES only)
        aslXLType2 = 15,            // X-L Type 2 (C with revocation values and a CertsAndCRLs timestamp, CAdES only)
        //aslA = 16,                  // A (archived)
        //aslExtendedBES = 17,        // Extended BES
        //aslExtendedEPES = 18,       // Extended EPES
        //aslExtendedT = 19,          // Extended T
        //aslExtendedC = 20,          // Extended C
        //aslExtendedXType1 = 22,     // Extended X (type 1, CAdES only)
        //aslExtendedXType2 = 23,     // Extended X (type 2, CAdES only)
        //aslExtendedXLType1 = 26,    // Extended XL (type 1, CAdES only)
        //aslExtendedXLType2 = 27,    // Extended XL (type 2, CAdES only)
        //aslExtendedA = 28           // Extended A
    }


    public enum SignatureLevelForXades
    {
        //aslUnknown = 0,
        //aslGeneric = 1,// Generic (this value applicable to XAdES signature only and corresponds to XML-DSIG signature)
        //aslBaselineB = 2,// Baseline B (B-B, basic)
        aslBaselineT = 3,// Baseline T (B-T, timestamped)
        aslBaselineLT = 4,// Baseline LT (B-LT, long-term)
        //aslBaselineLTA = 5,// Baseline LTA (B-LTA, long-term with archived timestamp)
        aslBES = 6,// BES (Basic Electronic Signature)
        //aslEPES = 7,// EPES (Electronic Signature with an Explicit Policy)
        //aslT = 8,//T,// (Timestamped)
        //aslC = 9,// C,// (T with revocation references)
        //aslX = 10,// X,// (C with SigAndRefs timestamp or RefsOnly timestamp) (this value applicable to XAdES signature only)
        //aslXL = 13,//	X-L (X with revocation values) (this value applicable to XAdES signature only)
        //aslA = 16,//	A (archived)
        //aslExtendedBES = 17,//	Extended BES
        //aslExtendedEPES = 18,//	Extended EPES
        //aslExtendedT = 19,//	Extended T
        //aslExtendedC = 20,//	Extended C
        //aslExtendedX = 21,//	Extended X (this value applicable to XAdES signature only)
        //aslExtendedXLong = 24,//	Extended X-Long (this value applicable to XAdES signature only)
        //aslExtendedXL = 25,//Extended X-L (this value applicable to XAdES signature only)
        //aslExtendedA = 28,//Extended A
    }


    /// <summary>
    /// V4 CAdES imza seviyeleri. Tüm CAdES seviyeleri desteklenir.
    /// </summary>
    public enum SignatureLevelForCadesV4
    {
        [Description("BES - Basic Electronic Signature")]
        BES = 1,

        [Description("EPES - Electronic Signature with Explicit Policy")]
        EPES = 2,

        [Description("ES-T - Timestamped")]
        T = 3,

        [Description("ES-C - T with revocation references")]
        C = 4,

        [Description("ES-X - C with timestamp")]
        X = 5,

        [Description("ES-XL - X with revocation values")]
        XL = 6,

        [Description("ES-A - Archived")]
        A = 7
    }


    /// <summary>
    /// Türk Elektronik İmza Kullanım Profilleri (Rehber v1.0).
    /// </summary>
    public enum CadesProfileV4
    {
        [Description("Profil yok")]
        None = 0,

        [Description("P1 - Sadece BES, policy yok")]
        P1 = 1,

        [Description("P2 - EPES+T, SİL (CRL), OID: 2.16.792.1.61.0.1.5070.3.1.1")]
        P2 = 2,

        [Description("P3 - EPES+XL/A, SİL (CRL), OID: 2.16.792.1.61.0.1.5070.3.2.1")]
        P3 = 3,

        [Description("P4 - EPES+XL/A, ÇİSDuP (OCSP), OID: 2.16.792.1.61.0.1.5070.3.3.1")]
        P4 = 4
    }


    /// <summary>
    /// V4 CAdES hash algoritmaları.
    /// </summary>
    public enum CadesHashAlgorithmV4
    {
        [Description("SHA-256")]
        SHA256 = 0,

        [Description("SHA-384")]
        SHA384 = 1,

        [Description("SHA-512")]
        SHA512 = 2
    }


    /// <summary>
    /// V4 PAdES imza seviyeleri (Baseline profili).
    /// PAdES'te C/X seviyeleri yoktur - DSS dictionary ile doğrudan B-LT/B-LTA'ya geçilir.
    /// </summary>
    public enum SignatureLevelForPadesV4
    {
        [Description("B-B - Baseline Basic")]
        BB = 1,

        [Description("B-T - Baseline Timestamp")]
        BT = 2,

        [Description("B-LT - Baseline Long-Term")]
        BLT = 3,

        [Description("B-LTA - Baseline Long-Term Archival")]
        BLTA = 4
    }


    /// <summary>
    /// V4 PAdES Türk profilleri.
    /// PAdES'te sadece P4 profili desteklenir (Rehber v1.0).
    /// P1/P2/P3 profilleri sadece CAdES/XAdES'te geçerlidir.
    /// </summary>
    public enum PadesProfileV4
    {
        [Description("Profil yok")]
        None = 0,

        [Description("P3 - EPES+B-LT/B-LTA, SİL (CRL), OID: 2.16.792.1.61.0.1.5070.3.2.1")]
        P3 = 3,

        [Description("P4 - EPES+B-LT/B-LTA, ÇİSDuP (OCSP), OID: 2.16.792.1.61.0.1.5070.3.3.1")]
        P4 = 4
    }


    /// <summary>
    /// V4 XAdES imza seviyeleri. XAdES'te C ve X seviyeleri yoktur.
    /// BES, EPES, T, XL, A desteklenir.
    /// Numara değerleri CAdES ile tutarlı (C=4, X=5 atlanıyor).
    /// </summary>
    public enum SignatureLevelForXadesV4
    {
        [Description("BES - Basic Electronic Signature")]
        BES = 1,

        [Description("EPES - Electronic Signature with Explicit Policy")]
        EPES = 2,

        [Description("ES-T - Timestamped")]
        T = 3,

        [Description("ES-XL - Extended Long-Term (revocation values dahil)")]
        XL = 6,

        [Description("ES-A - Archived")]
        A = 7
    }


    /// <summary>
    /// XAdES Türk Elektronik İmza Kullanım Profilleri (Rehber v1.0).
    /// CAdES ile aynı profiller ve OID'ler.
    /// P1: BES only, P2: T only, P3/P4: XL/A
    /// </summary>
    public enum XadesProfileV4
    {
        [Description("Profil yok")]
        None = 0,

        [Description("P1 - Sadece BES, policy yok")]
        P1 = 1,

        [Description("P2 - EPES+T, SİL (CRL), OID: 2.16.792.1.61.0.1.5070.3.1.1")]
        P2 = 2,

        [Description("P3 - EPES+XL/A, SİL (CRL), OID: 2.16.792.1.61.0.1.5070.3.2.1")]
        P3 = 3,

        [Description("P4 - EPES+XL/A, ÇİSDuP (OCSP), OID: 2.16.792.1.61.0.1.5070.3.3.1")]
        P4 = 4
    }


    /// <summary>
    /// XAdES imza modu.
    /// CAdES'teki bool Detached yerine üç mod desteklenir.
    /// Enveloped: İmza XML dokümanın içine gömülür (input XML olmalı).
    /// Enveloping: Veri imzanın ds:Object elementi içine konur.
    /// Detached: İmza ayrı dosyada, veri harici referansla işaret edilir.
    /// </summary>
    public enum XadesSignatureModeV4
    {
        [Description("Enveloped - İmza XML dokümanın içine gömülü")]
        Enveloped = 0,

        [Description("Enveloping - Veri imzanın içine konur (ds:Object)")]
        Enveloping = 1,

        [Description("Detached - İmza ayrı dosyada")]
        Detached = 2
    }

}

